# Generated by Django 4.0.3 on 2022-03-25 22:49

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='EntityRecordTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Entity_type', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MasterRecords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField()),
                ('violation', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('title', models.CharField(max_length=50)),
                ('case_number', models.CharField(max_length=8, validators=[django.core.validators.RegexValidator(message='Case Numbers must match the following format: XX-XXXXX ', regex='\\d{2}-\\d{5}')])),
                ('additional_detail', models.JSONField()),
                ('cad_call_number', models.IntegerField()),
                ('cad_id', models.IntegerField()),
                ('rms_case_number', models.IntegerField()),
                ('rms_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MasterRecordTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PersonTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='VehicleTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('is_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('plate', models.CharField(max_length=20)),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.vehicletypes')),
                ('master_record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.masterrecords')),
            ],
        ),
        migrations.CreateModel(
            name='Persons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.persontypes')),
                ('master_record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.masterrecords')),
            ],
        ),
        migrations.AddField(
            model_name='masterrecords',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.masterrecordtypes'),
        ),
        migrations.AddField(
            model_name='masterrecords',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='CustomFields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('value_type', models.CharField(max_length=50)),
                ('is_active', models.BooleanField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.masterrecordtypes')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('master_record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.masterrecords')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('image', models.FileField(upload_to='')),
                ('entity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.attachmenttypes')),
                ('master_record_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.masterrecords')),
            ],
        ),
    ]
