# Generated by Django 4.0.3 on 2022-03-28 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0002_formtypes_inputtypes_additionaldetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionaldetails',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.masterrecordtypes'),
        ),
        migrations.DeleteModel(
            name='FormTypes',
        ),
    ]
