# Generated by Django 4.0.3 on 2022-04-01 16:35

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_alter_attachmenttypes_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
