# Generated by Django 4.0.3 on 2022-04-01 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_example'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Example',
        ),
    ]
